docjeservices:
  web01:
    build:
      context: .
      dockerfile: Dockerfile
    image: web01
    container_name: web01
    networks:
      - asa-network

  web02:
    build:
      context: .
      dockerfile: Dockerfile.c02
    image: web02
    container_name: web02
    networks:
      - asa-network

  web03:
    build:
      context: .
      dockerfile: Dockerfile.c03
    image: web03
    container_name: web03
    networks:
      - asa-network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    image: proxy
    container_name: proxy

    ports:
      - "8080:80"
    depends_on:
      - web01
      - web02
    networks:
      - asa-network
#Docker Networks
networks:
  asa-network:
    driver: bridge
